Site/Controllers/OfferController.cs
using DAL.Entity;
using DAL.Models;
using DAL.Persistencia;
using EvoPdf;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml;

namespace Site.Controllers
{
    public class OfferController : Controller
    {
        // GET: Offer
        public ActionResult OfferEdit(int IdMoedaQuote, string qCode, int type, int ratear, int foto, int optQuote)
        {
            PreencheTela(IdMoedaQuote, qCode, type, ratear, foto, optQuote);
            return View();
        }

        protected void PreencheTela(int IdMoedaQuote, string qCode, int type, int ratear, int foto, int optQuote)
        {

            PreencheOfertaGeral(IdMoedaQuote, qCode, type, ratear, foto, optQuote);

            TBItineraryDAL tbdDal = new TBItineraryDAL();
            TBItinerary_HighlightsDAL tbDal = new TBItinerary_HighlightsDAL();
            CidadeDAL cdal = new CidadeDAL();

            Quotation _quotation = new QuotationDAL().ObterPorCode(qCode);
            Quotation_Grupo _qgrupo = new QuotationGrupoDAL().ObterPorIdQuotation(_quotation.Quotation_Id);

            FileTarifasDAL ftrDal = new FileTarifasDAL();
            FileTransfersDAL ftrsDal = new FileTransfersDAL();
            FileServExtraDAL fsextDal = new FileServExtraDAL();
            MealDAL mealdal = new MealDAL();

            List<TBItineraryDAL.CidadeHigh> cids = tbdDal.ListarTodosCidadesComHotels_(qCode, optQuote);
            foreach (var item in cids)
            {
                Cidade cid = cdal.ObterPorNome(item.Cidade);
                var lstvis = tbDal.ListarPorCidade_False(cid.CID_id, qCode, optQuote);
                if (lstvis.Count > 0)
                {
                    cids = cids.Where(s => s.Cidade != cid.CID_nome).ToList();
                }
            }
            foreach (var item in cids)
            {
                PreencheHightLightCity(item.Cidade, qCode, optQuote);
            }
            List<TBItinerary_Highlights> lstInto = tbDal.ListarTodos(qCode, optQuote);

            ViewBag.hightlights = cids;
            ViewBag.hightlightsInto = lstInto;

            ViewBag.lcidades = tbdDal.ListarTodosCidadesComHotels_String(qCode);

            ViewBag.qcode = qCode;
            ViewBag.optquote = optQuote;

            #region includes            

            int FileID = new FileCarrinhoDAL().RetornaFileObj(qCode).File_id;

            //FileTransfersDAL ftrDal = new FileTransfersDAL();
            Including_HighLightsDAL ihd = new Including_HighLightsDAL();

            List<Including_HighLights> lstInc = ihd.ListarPQuotation(qCode, optQuote);
            List<Including_HighLights> orderedList = new List<Including_HighLights>();

            var lstft = ftrDal.ListarTodosOpt(FileID, optQuote);
            int days = Convert.ToInt32(ftrsDal.MontaCarrinhoNewFile(FileID, optQuote)) + 1;

            if (lstInc.Count < 3)
            {
                ihd.ExcluirTodosCode(qCode, optQuote);

                ihd.InsertDefault_New(qCode, optQuote, days);
                orderedList = ihd.ListarPQuotation(qCode, optQuote);
            }
            else
            {
                orderedList = lstInc;
            }
            ViewBag.hightlightsIncluding = orderedList;
            #region comment            
            //if (lstInc.Count > 0)
            //{
            //    if (lstInc.Count(a => a.isNumDays == true) > 0)
            //    {
            //        orderedList.Add(lstInc.Where(a => a.isNumDays == true).Single());
            //    }
            //    else
            //    {
            //        orderedList.Add(new Including_HighLights()
            //        {
            //            ID = -1,
            //            Descricao = string.Format("{0} days / {1} nights", days, (days - 1))
            //        });
            //    }

            //    if (lstInc.Count(a => a.isNumTransfers == true) > 0)
            //    {
            //        orderedList.Add(lstInc.Where(a => a.isNumTransfers == true).Single());
            //    }
            //    else
            //    {
            //        orderedList.Add(new Including_HighLights()
            //        {
            //            ID = -2,
            //            Descricao = "Transfers in private with English-speaking guide(unless noted)"
            //        });
            //    }

            //    orderedList.AddRange(lstInc.Where(a => !(a.isNumDays == true) && !(a.isNumTransfers == true)).ToList());
            //}
            //else
            //{
            //    //ihd.InsertDefault(qCode, optQuote);
            //    //orderedList = ihd.ListarPQuotation(qCode, optQuote);
            //}
            #endregion

            #endregion

            #region not includes

            Discretion_HighLightsDAL dhd = new Discretion_HighLightsDAL();
            List<Discretion_HighLights> lstDis = dhd.ListarPQuotation(qCode, optQuote);

            if (lstDis.Count == 0)
            {
                dhd.InsertDefaults(qCode, optQuote);
                lstDis = dhd.ListarPQuotation(qCode, optQuote);
            }

            ViewBag.hightlightsDiscretion = lstDis;

            #endregion

            #region notes

            TBItinerary_InfoDAL tbinfod = new TBItinerary_InfoDAL();
            List<TBItinerary_Info> lstIti = tbinfod.ObterPorQuote(qCode, optQuote);
            if (lstIti.Count > 0 && lstIti.Where(s => s.Note != "" && s.Note != null).Count() > 0)
            {
                //ViewBag.EditorNotes = lstIti[0].Note;

                ViewBag.EditorNotes = lstIti.Where(s => s.Note != "" && s.Note != null).First().Note;
            }
            else
            {
                string str = "Thank you for choosing SouthAmerica.travel!<br><br>  You can view your itinerary by clicking on the \"full itinerary\" tab or by viewing the PDF version.  Our itineraries are completely customizable and can be changed to match your exact travel dates, hotel preferences, tour needs, etc.<br><br>";
                str = str + "Please check all entry requirements for each country you will visit based on your citizenship. You must have 6 months validity on your passport.<br><br>";
                str = str + "International and domestic flights are priced separately and your quote (per person) can be found under the \"flights\" tab.<br><br>";
                str = str + "I look forward to discussing the itinerary with you!";

                ViewBag.EditorNotes = str;
                SaveNote(qCode, optQuote, str);
            }

            #endregion

            #region images

            TBItinerary_HighlightsImages thi = new TBItinerary_HighlightsImagesDAL().ObterPorCode(qCode, optQuote);
            if (thi != null)
            {
                if (thi.FirstImage != null)
                    ViewBag.hgImg1 = "../../Galeria/TBItinerary/" + thi.FirstImage;
                else
                {
                    ViewBag.hgImg1 = "../../Galeria/noimage.jpg";
                }

                if (thi.LastImage != null)
                    ViewBag.hgImg2 = "../../Galeria/TBItinerary/" + thi.LastImage;
                else
                {
                    ViewBag.hgImg2 = "../../Galeria/noimage.jpg";
                }
            }
            else
            {
                var fileid = new FileCarrinhoDAL().ObterPorIdGrupo(_qgrupo.Quotation_Grupo_Id).File_id;
                var pars = insereFoto(fileid, optQuote, qCode);

                if (pars != "")
                {
                    ViewBag.hgImg1 = pars.Split('°')[0];
                    ViewBag.hgImg2 = pars.Split('°')[1];
                }
            }

            #endregion

            #region itinerary

            TBItinerary_SupplierDAL tbSpDal = new TBItinerary_SupplierDAL();

            List<itineraryModel> newitineraryEdit = new List<itineraryModel>();

            var itineraryEdit = tbdDal.ListarItinerary(qCode, optQuote);
            double dia = 1;
            DateTime dtnow = new DateTime();
            DateTime dtPrimeira = new DateTime();

            itineraryModel itemAnterior = null;

            itineraryModel itemNextN = null;
            itineraryModel itemNext = new itineraryModel();

            int countL = 0;

            foreach (var item in itineraryEdit)
            {

                if (item.titulo.Contains("Hotel Windsor Leme"))
                {

                }

                if (itemAnterior != null)
                {
                    itemAnterior = null;
                    countL++;
                    continue;
                }

                if (itemNextN != null && item.Flag.Equals("HOTEL"))
                {
                    itemNextN = null;
                    countL++;
                    continue;
                }

                itineraryModel it = new itineraryModel();
                it.cidade = item.cidade;
                it.dtfrom = (DateTime)item.dtfrom;
                it.dtTo = (DateTime)item.dtTo;
                it.Code = item.Code;
                it.idTabela = item.idTabela;
                it.optquote = item.optquote;
                it.Sid = item.Sid;
                it.tbItineraryID = item.tbItineraryID;
                it.NomePacote = item.NomePacote;

                if (item.NomePacote != null)
                {
                    it.DescPacote = retornaPacote(item.dtfrom, item.dtTo, item.Sid, item.NomePacote, item.idTabela, item.optquote, item.Code);
                }

                int tot = countL + 1;
                if (itineraryEdit.Count() != tot)
                    itemNext = itineraryEdit[tot];

Site/Views/Offer/_hightlight_discretion.cshtml
@foreach (var item in ViewBag.hightlightsDiscretion)
{
    <div class="row">
        <div class="col-md-12">
            <input type="button" id="btnEditHightLightDiscretion_@item.ID" class="btn btn-link openeditarhighlightDiscretion" value="@item.Descricao" name="@item.ID°@item.Descricao" title="Edit" /><button id="btnDeletarHighlightDiscretion" type="button" class="btn btn-xs btn-danger deletarhighlightDiscretion" value="@item.ID" title="Deletar"><span class="glyphicon glyphicon-trash"></span></button>
        </div>      
    </div>
}

<script type="text/javascript">
    $('.openeditarhighlightDiscretion').click(function () {
        var arr = $(this).attr('name').split('°');
        $('#txtNomeHightLightEditDiscretion').val($(this).val());
        $('#hdeHightLightIDDiscretion').val(arr[0]);
        $("#modalEditHighlightDiscretion").modal();
    });

    $('.deletarhighlightDiscretion').click(function () {

        var result = window.confirm('Deseja deletar esse item?');
        if (result == false) {
            e.preventDefault();
            return;
        };

        toastr.options = { closeButton: true, newestOnTop: false, progressBar: true, onclick: null, showDuration: "300", positionClass: "toast-top-right" };
        waitingDialog.show('Aguarde...', { dialogSize: 'sm', progressType: 'warning' });

        $.ajax({
            type: "GET",
            url: "@Url.Action("DeletarHighlightDiscretion", "Offer")",
            data: { idHighlightDiscretion: $(this).val() },
            success: function (d) {

                waitingDialog.hide();

                if (d.success) {
                    var $toast = toastr["success"](d.message, "ProSoftware");
                    $toastlast = $toast;

                    updateHightLightDiscretion();
                }
                else {
                    var $toast = toastr["error"](d.message, "ProSoftware");
                    $toastlast = $toast;
                }

            },
            error: function (xhr) { alert(xhr); }
        });

    });

</script>

Site/Views/Offer/_hightlight_including.cshtml
@foreach (var item in ViewBag.hightlightsIncluding)
{    
    <div class="row">
        <div class="col-md-12">
            <input type="button" id="btnEditHightLightIncluding_@item.ID" class="btn btn-link openeditarhighlightincluding" value="@item.Descricao" name="@item.ID°@item.Descricao" title="Edit" /><button id="btnDeletarHighlightIncluding" type="button" class="btn btn-xs btn-danger deletarhighlightIncluding" value="@item.ID" title="Deletar"><span class="glyphicon glyphicon-trash"></span></button>
        </div>       
    </div>        
}

<script type="text/javascript">
    $('.openeditarhighlightincluding').click(function () {
        var arr = $(this).attr('name').split('°');
        $('#txtNomeHightLightEditIncluding').val($(this).val());
        $('#hdeHightLightIDIncluding').val(arr[0]);
        $("#modalEditHighlightIncluding").modal();
    });

    $('.deletarhighlightIncluding').click(function () {

        var result = window.confirm('Deseja deletar esse item?');
        if (result == false) {
            e.preventDefault();
            return;
        };

        toastr.options = { closeButton: true, newestOnTop: false, progressBar: true, onclick: null, showDuration: "300", positionClass: "toast-top-right" };
        waitingDialog.show('Aguarde...', { dialogSize: 'sm', progressType: 'warning' });

        $.ajax({
            type: "GET",
            url: "@Url.Action("DeletarHighlightIncluding", "Offer")",
            data: { idHighlightIncluding: $(this).val() },
            success: function (d) {

                waitingDialog.hide();

                if (d.success) {
                    var $toast = toastr["success"](d.message, "ProSoftware");
                    $toastlast = $toast;

                    updateHightLightIncluding();
                }
                else {
                    var $toast = toastr["error"](d.message, "ProSoftware");
                    $toastlast = $toast;
                }

            },
            error: function (xhr) { alert(xhr); }
        });

    });

</script>

Site/Views/Offer/_hightlights_city.cshtml
@foreach (var item in ViewBag.hightlights)
{
    <li>@item.Cidade <button id="btnDeletarHighlightCity" type="button" class="btn btn-xs btn-danger deletarhighlightcity" value="@item.Cidade" title="Deletar"><span class="glyphicon glyphicon-trash"></span></button></li>

    var lstinto = ViewBag.hightlightsInto as List<DAL.Entity.TBItinerary_Highlights>;

    <ul style="padding-left: 10px;">
        @foreach (var itemInto in lstinto.Where(s => s.Cidade_ID == item.idCidade).ToList())
        {
            <li style="list-style: none; display: block;" id="li_@itemInto.Id">
                <div style="width: 80%; display: inline-block">
                    <input type="button" id="btnEditHightLight_@itemInto.Id" class="btn btn-link openeditarhighlight" value="@itemInto.Highlight" name="@itemInto.Id°@itemInto.Highlight" title="Edit" />
                    <button id="btnDeletarHighlight" type="button" class="btn btn-xs btn-danger deletarhighlight" value="@itemInto.Id" title="Deletar"><span class="glyphicon glyphicon-trash"></span></button>
                </div>
            </li>
        }
    </ul>
}


<script type="text/javascript">

    $('.openeditarhighlight').click(function () {
        var arr = $(this).attr('name').split('°');
        $('#txtNomeHightLightEdit').val($(this).val());
        $('#hdeHightLightID').val(arr[0]);
        $("#modalEditHighlight").modal();
    });


    $('.deletarhighlightcity').click(function () {
        var result = window.confirm('Deseja deletar esse item?');
        if (result == false) {
            e.preventDefault();
            return;
        };

        toastr.options = { closeButton: true, newestOnTop: false, progressBar: true, onclick: null, showDuration: "300", positionClass: "toast-top-right" };
        waitingDialog.show('Aguarde...', { dialogSize: 'sm', progressType: 'warning' });

        $.ajax({
            type: "GET",
            url: "@Url.Action("DeletarHighlightCity", "Offer")",
            data: {
                cidade: $(this).val(),
                qCode: $('#qCodeHD').val(),
                optQuote: $('#optquoteHD').val() },
            success: function (d) {

                waitingDialog.hide();

                if (d.success) {
                    var $toast = toastr["success"](d.message, "ProSoftware");
                    $toastlast = $toast;

                    updateHightLightCity();
                }
                else {
                    var $toast = toastr["error"](d.message, "ProSoftware");
                    $toastlast = $toast;
                }

            },
            error: function (xhr) { alert(xhr); }
        });

    });


     $('.deletarhighlight').click(function () {

        var result = window.confirm('Deseja deletar esse item?');
        if (result == false) {
            e.preventDefault();
            return;
        };

        toastr.options = { closeButton: true, newestOnTop: false, progressBar: true, onclick: null, showDuration: "300", positionClass: "toast-top-right" };
        waitingDialog.show('Aguarde...', { dialogSize: 'sm', progressType: 'warning' });

        $.ajax({
            type: "GET",
            url: "@Url.Action("DeletarHighlight", "Offer")",
            data: { idHighlight: $(this).val() },
            success: function (d) {

                waitingDialog.hide();

                if (d.success) {
                    var $toast = toastr["success"](d.message, "ProSoftware");
                    $toastlast = $toast;

                    updateHightLightCity();
                }
                else {
                    var $toast = toastr["error"](d.message, "ProSoftware");
                    $toastlast = $toast;
                }

            },
            error: function (xhr) { alert(xhr); }
        });

    });

</script>

Site/Views/Offer/_hoteis.cshtml
@model IEnumerable<DAL.Models.HoteisOfferModel>

@if (Model.Count() > 0)
{
    foreach (var item in Model)
    {

        <div class="row">
            <div class="col-md-6">
                @if (!item.imgStars.ToString().Contains("semfoto"))
                {
                    <img src="@item.imgStars" class="img-responsive" />
                }
                <span style="font-size: 26px;color: #727272;">
                    @item.nomeHotel
                </span>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <span style="width: 100%;font-style: italic;font-family: 'Lato', Helvetica, Arial, sans-serif;font-size: 14px;color: #31baef;">
                    @item.cidade
                </span>
            </div>
        </div>
        <hr style="border: dashed #d6d6d6;border-width: 1px 0 0;height: 0px;" />
        <br />

        <div class="row">
            <div class="col-md-6">
                <span style="font-family: 'Lato', Helvetica, Arial, sans-serif;">
                    @Html.Raw(item.descricaoHotel)
                </span>
            </div>
            <div class="col-md-6">
                <img src="@item.imgHotel" class="img-thumbnail" style="width:240px;height:214px;" />
            </div>
        </div>
        <br /><br />

        foreach (var item2 in item.lstAmenities)
        {
            <div class="row">
                <div class="col-md-2">
                    <span style="font-weight: bold;font-size: 16px;">
                        @item2.S_GroupAmenities_Name
                    </span>
                </div>

                <div class="col-md-6" style="padding:10px; border-radius: 4px;border: 1px solid #dddddd;">

                    <div class="row">


                        @foreach (var item3 in item.lstAmenitiesItens.Where(s => s.S_GroupAmenities_ID == item2.S_GroupAmenities_ID))
                        {
                            <div class="col-md-1">
                                <img src="http://sp.southamerica.travel/tierratmvc/iconsAmenities/@item3.S_Amenities_imgNome" class="img-responsive" style="width: 20px;height:20px;margin-left:20px;" />
                            </div>
                            <div class="col-md-3">
                                @item3.S_Amenities_nome
                            </div>
                        }


                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-9">
                    <hr style="border: dashed #d6d6d6;border-width: 1px 0 0;height: 0px;" />
                </div>
            </div>

        }



        <br /><br />
    }
}

Site/Views/Offer/_hoteisPDF.cshtml
@model IEnumerable<DAL.Models.HoteisOfferModel>

@if (Model.Count() > 0)
{
    foreach (var item in Model)
    {

        <div class="row">
            <div class="col-md-6">
                @if (!item.imgStars.ToString().Contains("semfoto"))
                {
                    <img src="@item.imgStars" class="img-responsive" />
                }
                <span style="font-size: 26px;color: #727272;">
                    @item.nomeHotel
                </span>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <span style="width: 100%;font-style: italic;font-family: 'Lato', Helvetica, Arial, sans-serif;font-size: 14px;color: #31baef;">
                    @item.cidade
                </span>
            </div>
        </div>
        <hr style="border: dashed #d6d6d6;border-width: 1px 0 0;height: 0px;" />
        <br />

        <div class="row">
            <div class="col-md-6">
                <span style="font-family: 'Lato', Helvetica, Arial, sans-serif;">
                    @Html.Raw(item.descricaoHotel)
                </span>
            </div>
            <div class="col-md-6">
                <img src="@item.imgHotel" class="img-thumbnail" style="width:240px;height:214px;" />
            </div>
        </div>
        <br /><br />

        foreach (var item2 in item.lstAmenities)
        {
            <div class="row">
                <div class="col-md-2">
                    <span style="font-weight: bold;font-size: 16px;">
                        @item2.S_GroupAmenities_Name
                    </span>
                </div>

                <div class="col-md-8" style="padding:10px; border-radius: 4px;border: 1px solid #dddddd;">

                    <div class="row">


                        @foreach (var item3 in item.lstAmenitiesItens.Where(s => s.S_GroupAmenities_ID == item2.S_GroupAmenities_ID))
                        {
                            <div class="col-md-1">
                                <img src="http://54.232.209.130/TierraTMVC/iconsAmenities/@item3.S_Amenities_imgNome" class="img-responsive" style="width: 20px;height:20px;" />
                            </div>
                            <div class="col-md-3">
                                @item3.S_Amenities_nome
                            </div>
                        }


                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-9">
                    <hr style="border: dashed #d6d6d6;border-width: 1px 0 0;height: 0px;" />
                </div>
            </div>

        }



        <br /><br />
    }
}