Site/Controllers/SupplierController.cs
using BLL.Utils;
using DAL.Entity;
using DAL.Models;
using DAL.Persistencia;
using Site.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Site.Controllers
{
    [Authorize]
    public class SupplierController : Controller
    {
        // GET: Supplier
        public ActionResult Index()
        {
            StartSupplier();
            return View("Suppliers");
        }

        public Usuarios ObterUser()
        {
            try
            {
                FormsIdentity id = (FormsIdentity)System.Web.HttpContext.Current.User.Identity;
                FormsAuthenticationTicket ticket = id.Ticket;
                return new UsuarioDAL().ObterPorEmail(ticket.Name);
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return null;
            }
        }

        #region Autocompletes

        public ActionResult ObterQuotations(string term, int user_id)
        {
            try
            {
                List<string> quots = new List<string>();

                //if (term.Equals("*"))
                //    quots = new QuotationDAL().ListarTodosString(term, user_id);
                //else
                quots = new QuotationDAL().ListarTodosString(term, user_id).Take(100).ToList();

                return Json(quots, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
                return null;
            }
        }

        public ActionResult ObterQuotations_copia(string term)
        {
            try
            {
                List<string> quots = new List<string>();
                quots = new QuotationDAL().ListarTodosString(term).Take(100).ToList();

                return Json(quots, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
                return null;
            }
        }

        public ActionResult ObterClientes(string term)
        {
            try
            {
                List<string> cls = new ClienteDAL().ListarTodos(term).Select(s => s.Cliente_nome).Distinct().Take(100).ToList();
                return Json(cls, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
                return null;
            }
        }

        public ActionResult ObterCidades(string term)
        {
            try
            {
                List<string> cls = new List<string>();

                if (term.Equals("*"))
                    cls = new CidadeDAL().ListarTodos().OrderBy(s => s.CID_nome).Select(s => s.CID_nome).Distinct().ToList();
                else
                    cls = new CidadeDAL().ListarTodos(term).Select(s => s.CID_nome).Distinct().Take(100).ToList();


                return Json(cls, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
                return null;
            }
        }

        public ActionResult ObterTransfers(string term, string cidade)
        {
            try
            {
                ServicoDAL ftd = new ServicoDAL();
                List<string> cls = new List<string>();

                if (!cidade.Equals(""))
                    cls = ftd.ListarTodosTrf(term, new CidadeDAL().ObterPorNome(cidade).CID_id).Select(s => s.Servicos_Nome).Distinct().ToList();
                else
                    cls = ftd.ListarTodosTrf(term).Select(s => s.Servicos_Nome).Distinct().Take(200).ToList();

                return Json(cls, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
                return null;
            }
        }

        public ActionResult ObterTours(string term, string cidade)
        {
            try
            {
                ServicoDAL ftd = new ServicoDAL();
                List<string> cls = new List<string>();

                if (!cidade.Equals(""))
                    cls = ftd.ListarTodosTor(term, new CidadeDAL().ObterPorNome(cidade).CID_id).Select(s => s.Servicos_Nome).Distinct().ToList();
                else
                    cls = ftd.ListarTodosTor(term).Select(s => s.Servicos_Nome).Distinct().Take(200).ToList();

                return Json(cls, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
                return null;
            }
        }

        public ActionResult ObterSuppliers(string term)
        {
            try
            {
                List<string> cls = new List<string>();

                cls = new SupplierDAL().ListarTodos(term).Select(s => s.S_nome).OrderBy(s => s).ToList();

                return Json(cls, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
                return null;
            }
        }

        public ActionResult ObterHoteis(string term, string cidade)
        {
            try
            {
                SupplierDAL ftd = new SupplierDAL();
                List<string> lst = new List<string>();

                if (!cidade.Equals(""))
                {
                    lst = ftd.FindAllTipo(term, 1, new CidadeDAL().ObterPorNome(cidade).CID_id).OrderBy(s => s.S_nome).Select(s => s.S_nome).ToList();
                }
                else
                {
                    lst = ftd.FindAllTipo(term, 1).OrderBy(s => s.S_nome).Select(s => s.S_nome).ToList();
                }

                return Json(lst, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
                return null;
            }
        }

        public ActionResult ObterPaxsGroups(string term, int user_id)
        {
            try
            {
                List<string> cls = new List<string>();

                cls = new QuotationGrupoDAL().ListarPaxsGroup(user_id, 0, term).ToList();

                return Json(cls, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
                return null;
            }
        }

        public ActionResult ObterSuppliers_Filtros(string term, int idStatus, int idTipoSupplier, int TipoPesquisa, int idCidade)
        {
            try
            {
                List<string> cls = new List<string>();

                cls = new SupplierDAL().ListarSupplier_Filtros(term, idStatus, idTipoSupplier, TipoPesquisa, idCidade);

                return Json(cls, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
                return null;
            }
        }

        public ActionResult ObterCategorias(string term)
        {
            try
            {
                TarifCategoriaDAL t = new TarifCategoriaDAL();
                List<Tarif_Categoria> tc = t.ListarTodos(term);

                List<string> lista = new List<string>();

                foreach (Tarif_Categoria p in tc)
                {
                    lista.Add(p.Tarif_categoria_nome);
                }

                return Json(lista, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
                return null;
            }
        }

        #endregion

        #region Supplier

        public void StartSupplier()
        {

            SupplierDAL sppDal = new SupplierDAL();
            var lstSpp = sppDal.ListarTodos();

            var spp = new Supplier();
            spp.S_id = 0;
            ViewData["supplier"] = spp;
            ViewBag.ResponsavelSupplier = lstSpp;
            ViewBag.MoedaSupplier = new MoedaDAL().ListarTodos();
            ViewBag.TipoSupplier = new TipoSuplsDAL().ListarTodos();
            ViewBag.CategoriaEscSupplier = new CategoriaEscritaDAL().ListarTodos("");
            ViewBag.CategoriaSupplier = new CategoriaDAL().ListarTodos();
            ViewBag.RedeSupplier = new RedeDAL().ListarTodos();
            ViewBag.StatusSupplier = new S_StatusDAL().ListarTodos();

            ViewBag.classificacaoLodge = new ClassificacaoLodgeDAL().ListarTodos();

            PaisDAL pdal = new PaisDAL();
            var pais = pdal.ListarTodos();
            ViewBag.PaisSupplier = pais;

            var paisfiltro = pdal.ListarTodosComSupplier();
            ViewBag.PaisSupplierFiltro = paisfiltro;

            ViewBag.CidadeSupplier = new CidadeDAL().ListarTodos(pais.First().PAIS_id);

            ViewBag.CidadeSupplierFiltro = new CidadeDAL().ListarTodosSupplier(paisfiltro.First().PAIS_id);

            ViewBag.MercadoSppTarifas = new MercadoDAL().ListarTodos();
            ViewBag.BaseTarifariaSppTarifas = new BaseTarifariaDAL().ListarTodos();

            ViewBag.TipoTransporteBases = new TipoTransporteDAL().ListarTodos();
            ViewBag.TipoBases = new TipoBaseDAL().ListarTodos();

            ViewBag.ResponsavelSppTarifas = lstSpp;
        }

        public string ObterCidadesSupplierDrop(int idPais)
        {
            try
            {
                SupplierDAL sDal = new SupplierDAL();
                CidadeDAL cDal = new CidadeDAL();
                var cid = cDal.ListarTodos(idPais);

                string drop = "";
                drop = drop + "<option value=\"0\">Selecione...</option>";
                foreach (var item in cid)
                {

Site/Views/Supplier/_amenities.cshtml
<form role="form" id="form-amenities" method="post" action="javascript:func()">

    <input id="SidAmenitiesSpp" type="hidden" />

    <div class="nav-tabs-custom">
        <ul class="nav nav-tabs">
            <li class="active"><a href="#tabAment_1" data-toggle="tab">Activities</a></li>
            <li><a href="#tabAment_2" data-toggle="tab">Children Facilities</a></li>
            <li><a href="#tabAment_3" data-toggle="tab">General</a></li>
            <li><a href="#tabAment_4" data-toggle="tab">General Information</a></li>
            <li><a href="#tabAment_5" data-toggle="tab">Internet</a></li>
            <li><a href="#tabAment_6" data-toggle="tab">Services</a></li>
            <li><a href="#tabAment_7" data-toggle="tab">Suite</a></li>
        </ul>
        <div class="tab-content">

            <div class="tab-pane active" id="tabAment_1">

                @{ List<int> g = ViewBag.lstIdsSpp; }
                <div class="row">
                    @foreach (var item in ViewBag.AmenitiesActivities)
                    {
                        <div class="col-md-3">

                            @if (g.Contains(item.S_Amenities_id))
                            {
                                <input type="checkbox" checked="checked" class="chkAmenities" value="@item.S_Amenities_id" />
                            }
                            else
                            {
                                <input type="checkbox" class="chkAmenities" value="@item.S_Amenities_id" />
                            }

                            <img src="@string.Format("iconsAmenities/{0}", item.S_Amenities_imgNome)" />
                            <small>@item.S_Amenities_nome</small>
                        </div>
                    }
                </div>

            </div>

            <div class="tab-pane" id="tabAment_2">
                <div class="row">
                    @foreach (var item in ViewBag.AmenitiesChildrenFacilities)
                    {
                        <div class="col-md-3">
                            @if (g.Contains(item.S_Amenities_id))
                            {
                                <input type="checkbox" checked="checked" class="chkAmenities" value="@item.S_Amenities_id" />
                            }
                            else
                            {
                                <input type="checkbox"  class="chkAmenities" value="@item.S_Amenities_id" />
                            }

                            <img src="@string.Format("iconsAmenities/{0}", item.S_Amenities_imgNome)" />
                            <small>@item.S_Amenities_nome</small>
                        </div>
                    }
                </div>
            </div>

            <div class="tab-pane" id="tabAment_3">
                <div class="row">
                    @foreach (var item in ViewBag.AmenitiesGeneral)
                    {
                        <div class="col-md-3">
                            @if (g.Contains(item.S_Amenities_id))
                            {
                                <input type="checkbox" checked="checked" class="chkAmenities" value="@item.S_Amenities_id" />
                            }
                            else
                            {
                                <input type="checkbox" class="chkAmenities" value="@item.S_Amenities_id" />
                            }
                            <img src="@string.Format("iconsAmenities/{0}", item.S_Amenities_imgNome)" />
                            <small>@item.S_Amenities_nome</small>
                        </div>
                    }
                </div>
            </div>

            <div class="tab-pane" id="tabAment_4">
                <div class="row">
                    @foreach (var item in ViewBag.AmenitiesGeneralInfor)
                    {
                        <div class="col-md-3">
                            @if (g.Contains(item.S_Amenities_id))
                            {
                                <input type="checkbox" checked="checked" class="chkAmenities" value="@item.S_Amenities_id" />
                            }
                            else
                            {
                                <input type="checkbox"  class="chkAmenities" value="@item.S_Amenities_id" />
                            }
                            <img src="@string.Format("iconsAmenities/{0}", item.S_Amenities_imgNome)" />
                            <small>@item.S_Amenities_nome</small>
                        </div>
                    }
                </div>
            </div>

            <div class="tab-pane" id="tabAment_5">
                <div class="row">
                    @foreach (var item in ViewBag.AmenitiesInternet)
                    {
                        <div class="col-md-3">
                            @if (g.Contains(item.S_Amenities_id))
                            {
                                <input type="checkbox" checked="checked" class="chkAmenities" value="@item.S_Amenities_id" />
                            }
                            else
                            {
                                <input type="checkbox" class="chkAmenities" value="@item.S_Amenities_id" />
                            }
                            <img src="@string.Format("iconsAmenities/{0}", item.S_Amenities_imgNome)" />
                            <small>@item.S_Amenities_nome</small>
                        </div>
                    }
                </div>
            </div>

            <div class="tab-pane" id="tabAment_6">
                <div class="row">
                    @foreach (var item in ViewBag.AmenitiesServices)
                    {
                        <div class="col-md-3">
                            @if (g.Contains(item.S_Amenities_id))
                            {
                                <input type="checkbox" checked="checked" class="chkAmenities" value="@item.S_Amenities_id" />
                            }
                            else
                            {
                                <input type="checkbox" class="chkAmenities" value="@item.S_Amenities_id" />
                            }
                            <img src="@string.Format("iconsAmenities/{0}", item.S_Amenities_imgNome)" />
                            <small>@item.S_Amenities_nome</small>
                        </div>
                    }
                </div>
            </div>

            <div class="tab-pane" id="tabAment_7">
                <div class="row">
                    @foreach (var item in ViewBag.AmenitiesSuite)
                    {
                        <div class="col-md-3">
                            @if (g.Contains(item.S_Amenities_id))
                            {
                                <input type="checkbox" checked="checked" class="chkAmenities" value="@item.S_Amenities_id" />
                            }
                            else
                            {
                                <input type="checkbox" class="chkAmenities" value="@item.S_Amenities_id" />
                            }
                            <img src="@string.Format("iconsAmenities/{0}", item.S_Amenities_imgNome)" />
                            <small>@item.S_Amenities_nome</small>
                        </div>
                    }
                </div>
            </div>

        </div>
    </div>
</form>


<script type="text/javascript">

    $('.chkAmenities').click(function () {
        $.get("@Url.Action("SalvaAmenities", "Supplier")", { Sid: $('#idsupplier').val() , IDamenities: $(this).val() }, function (d) {
            if (d.success) {
                alert(d.message);
                //refreshAmenitiesSpp();
            }
        });        
    });
    
</script>

Site/Views/Supplier/_blackout_add.cshtml
@model DAL.Entity.S_Mercado_Periodo_Black

<form role="form" id="form-Blackout" method="post" action="javascript:func()">

    <input id="PeriodoBlackID" type="hidden" name="S_merc_periodo_black_id" value="@Model.S_merc_periodo_black_id" />
    <input id="SIDBlack" type="hidden" name="S_id" value="@Model.S_id" />

    <div class="row">
        <div class="col-md-6">
            <label for="txtDataFromBlack">Data From</label>
            <input id="txtDataFromBlack" type="date" name="S_merc_periodo_black_from" class="form-control" value="@string.Format("{0:yyyy-MM-dd}", Model.S_merc_periodo_black_from)" required />
        </div>
        <div class="col-md-6">
            <label for="txtDataToBlack">Data To</label>
            <input id="txtDataToBlack" name="S_merc_periodo_black_to" type="date" class="form-control" value="@string.Format("{0:yyyy-MM-dd}", Model.S_merc_periodo_black_to)" required />
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-6">
            <label for="ddlMercadoBlack">Mercado</label>
            <select id="ddlMercadoBlack" class="form-control" name="Mercado_id">
                @foreach (var item in ViewBag.MercadoBlack)
                {
                <option value="@item.Mercado_id">@item.Mercado_nome</option>
                }
            </select>
        </div>
        <div class="col-md-6">
            <label for="ddlBaseTarifariaBlack">BaseTarifaria</label>
            <select id="ddlBaseTarifariaBlack" class="form-control" name="BaseTarifaria_id">
                @foreach (var item in ViewBag.BaseTarifariaBlack)
                {
                <option value="@item.BaseTarifaria_id">@item.BaseTarifaria_nome</option>
                }
            </select>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-12">
            <label for="txtObsBlack">Remarks</label>
            <textarea id="txtObsBlack" class="form-control" name="S_merc_periodo_black_obs" placeholder="Obs"></textarea>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-2">
            <input id="btnSalvarPeriodoBlack" type="submit" class="btn btn-primary" title="Salvar" value="Salvar" style="border-radius:0px;" />
        </div>
    </div>
</form>

<br />

<div class="row">

    <div class="col-md-12">        

        <table class="table table-bordered table-striped">

            <thead>

                <tr>
                    <th><small>From</small></th>
                    <th><small>To</small></th>
                    <th><small>Obs</small></th>
                    <th><small>Del</small></th>
                </tr>

            </thead>

            <tbody>                
                @foreach (var item in ViewBag.LstBalcks)
                {
                    <tr>
                        <td><small>@string.Format("{0:dd/MM/yyyy}", item.S_merc_periodo_black_from)</small></td>
                        <td><small>@string.Format("{0:dd/MM/yyyy}", item.S_merc_periodo_black_to)</small></td>
                        <td><small>@item.S_merc_periodo_black_obs</small></td>
                        <td>
                            <small>
                                <button id="btnDeletar" type="button" value='@item.S_merc_periodo_black_id' class="btn btn-xs btn-danger deletarblackout" title="Deletar Periodo Blackout"><span class="glyphicon glyphicon-trash"></span></button>
                            </small>
                        </td>
                    </tr>                  
                }

            </tbody>

        </table>

    </div>

</div>

<script type="text/javascript">

    if(@Model.S_merc_periodo_black_id != 0)
    {
        $('#ddlMercadoBlack').val(@Model.Mercado_id);
        $('#ddlBaseTarifariaBlack').val(@Model.BaseTarifaria_id);
    }

    $('.deletarblackout').click(function(){
        var result = window.confirm('Deseja deletar esse periodo?');
        if (result == false) {
            e.preventDefault();
            return;
        };

        toastr.options = { closeButton: true, newestOnTop: false, progressBar: true, onclick: null, showDuration: "300", positionClass: "toast-top-right" };

        $.get("@Url.Action("ExluirPeriodoBlack", "Supplier")", { IDBlack: $(this).val() }, function (d) {
            if (d.success) {
                var $toast = toastr["success"](d.message, "Prosoftware");
                $toastlast = $toast;
                refreshGridBlackout();
            }
            else {
                var $toast = toastr["error"](d.message, "Prosoftware");
                $toastlast = $toast;
            }

        });
    });

    $('#form-Blackout').submit(function () {

        if($('#idsupplier').val() == 0){
            alert("Favor selecionar um supplier primeiro");
            return false;
        }

        $('#btnSalvarPeriodoBlack').attr("disabled", "disabled");
        $('#btnSalvarPeriodoBlack').html('Aguarde...');

        toastr.options = { closeButton: true, newestOnTop: false, progressBar: true, onclick: null, showDuration: "300", positionClass: "toast-top-right" };

        $('#SIDBlack').val($('#idsupplier').val());

        var mod = $(this).serialize();

        $.ajax({
            url: "@Url.Action("SalvarPeriodoBlack", "Supplier")",
            data: mod,
            type: "POST",
            success: function (d) {
                if (d.success) {
                    var $toast = toastr["success"](d.message, "Prosoftware");
                    $toastlast = $toast;
                    refreshGridBlackout();
                }
                else {
                    var $toast = toastr["error"](d.message, "Prosoftware");
                    $toastlast = $toast;
                }

                $('#btnSalvarPeriodoBlack').removeAttr("disabled", "disabled");
                $('#btnSalvarPeriodoBlack').html('Salvar');
            },
            error: function (XHR) {
                alert(XHR);

                $('#btnSalvarPeriodoBlack').removeAttr("disabled", "disabled");
                $('#btnSalvarPeriodoBlack').html('Salvar');
            }
        });
    });

</script>

Site/Views/Supplier/_condPagamento.cshtml
<form role="form" id="form-condPag" method="post" action="javascript:func()">

    <input id="idSupplierCondPag" type="hidden" name="S_id" />

    <div class="row">
        <div class="col-md-6">
            <label for="txtFonteCambio">Fonte Cambio</label>
            <input id="txtFonteCambio" name="CondPag_fontecambio" type="text" class="form-control" required />
        </div>
        <div class="col-md-6">
            <label for="ddlTipoCambio">Tipo Cambio</label>
            <select id="ddlTipoCambio" class="form-control" name="CondPag_tipocambio">
                <option value="0">Sem tipo...</option>
                <option value="Comercial Compra">Comercial Compra</option>
                <option value="Comercial Venda">Comercial Venda</option>
                <option value="Turismo Compra">Turismo Compra</option>
                <option value="Turismo Venda">Turismo Venda</option>
                <option value="Paralelo Compra">Paralelo Compra</option>
                <option value="Paralelo Venda">Paralelo Venda</option>
                <option value="Cambio Empresa">Cambio Empresa</option>
                <option value="Travel Cheque">Travel Cheque</option>
                <option value="Travel Cheque US$">Travel Cheque US$</option>
            </select>
        </div>
    </div>
    <br />    
    <div class="row">
        <div class="col-md-12">
            <label for="rdpDtCambioTroca">Data Cambio de Troca</label>           
                <br />
                <input id="rdoDataCambio" class="rdoDataCambioCL" name="rdoDataCambio" type="radio" checked="checked" value="in" /> Chek-in
                <input id="rdoDataCambio" class="rdoDataCambioCL" name="rdoDataCambio" type="radio" value="out" /> Chek-out                
                <input id="hddrdoDataCambio" type="hidden" name="CondPag_datatroca" />            
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-12">
            <label for="txtPrazoFaturamento">Prazo Faturamento</label>
            <input id="txtPrazoFaturamento" name="CondPag_prazofaturamento" type="text" class="form-control" required />
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-4">
            <label for="txtBanco">Banco</label>
            <input id="txtBanco" name="CondPag_prazofaturamento" type="text" class="form-control" required />
        </div>
        <div class="col-md-4">
            <label for="txtAgencia">Agência</label>
            <input id="txtAgencia" name="CondPag_agencia" type="text" class="form-control" required />
        </div>
        <div class="col-md-4">
            <label for="txtConta">Conta</label>
            <input id="txtConta" name="CondPag_conta" type="text" class="form-control" required />
        </div>
    </div>
    <br />   
    <div class="row">
        <div class="col-md-2">
            <input id="btnSalvarCondPag" type="submit" class="btn btn-primary" title="Salvar" value="Salvar" style="border-radius:0px;" />
        </div>
    </div>

</form>

<br />

<div class="row">

    <div class="col-md-12">

        <table class="table table-bordered table-striped">

            <thead>

                <tr>
                    <th><small>Fonte</small></th>
                    <th><small>Tipo Cambio</small></th>
                    <th><small>Data Cambio Troc</small></th>
                    <th><small>Prazo Fat</small></th>
                    <th><small>Deletar</small></th>
                </tr>

            </thead>

            <tbody>

                @foreach (var item in ViewBag.lstCondPag)
                {
                    <tr>
                        <td><small>@item.CondPag_fontecambio</small></td>
                        <td><small>@item.CondPag_tipocambio</small></td>
                        <td><small>@item.CondPag_datatroca</small></td>
                        <td><small>@item.CondPag_prazofaturamento</small></td>
                        <td>
                            <small>
                                <button type="button" value='@item.CondPag_id' class="btn btn-xs btn-danger deletarcondPag" title="Deletar Cond Pagamento"><span class="glyphicon glyphicon-trash"></span></button>
                            </small>
                        </td>
                    </tr>
                }

            </tbody>

        </table>

    </div>

</div>


<script type="text/javascript">

    $('#hddrdoDataCambio').val("in");

    $('.rdoDataCambioCL').change(function () {
        if ($("input[name='rdoDataCambio']:checked").val() == "in") {
            $('#hddrdoDataCambio').val("in");

        } else {
            $('#hddrdoDataCambio').val("out");
        }
    });


    $('#form-condPag').submit(function () {

        toastr.options = { closeButton: true, newestOnTop: false, progressBar: true, onclick: null, showDuration: "300", positionClass: "toast-top-right" };
        var mod = $(this).serialize();

        $('#btnSalvarCondPag').attr("disabled", "disabled");
        $('#btnSalvarCondPag').html('Aguarde...');

        $.ajax({
            url: "@Url.Action("SalvarCond", "Supplier")",
            data: mod,
            type: "POST",
            success: function (d) {
                if (d.success) {
                    var $toast = toastr["success"](d.message, "Prosoftware");
                    $toastlast = $toast;
                    AtualizaCondPag();
                }
                else {
                    var $toast = toastr["error"](d.message, "Prosoftware");
                    $toastlast = $toast;
                }

                $('#btnSalvarCondPag').removeAttr("disabled", "disabled");
                $('#btnSalvarCondPag').html('Salvar');
            },
            error: function (XHR) {
                alert(XHR);
                $('#btnSalvarCondPag').removeAttr("disabled", "disabled");
                $('#btnSalvarCondPag').html('Salvar');
            }
        });

    });


    $('.deletarcondPag').click(function () {
        var result = window.confirm('Deseja deletar essa Cond Pagamento?');
        if (result == false) {
            e.preventDefault();
            return;
        };

        toastr.options = { closeButton: true, newestOnTop: false, progressBar: true, onclick: null, showDuration: "300", positionClass: "toast-top-right" };

        $.get("@Url.Action("ExluirCondPag", "Supplier")", { idCondPag: $(this).val() }, function (d) {
            if (d.success) {
                var $toast = toastr["success"](d.message, "Prosoftware");
                $toastlast = $toast;
                AtualizaCondPag();
            }
            else {
                var $toast = toastr["error"](d.message, "Prosoftware");
                $toastlast = $toast;
            }

        });
    });

</script>