Site/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAL.Models;
using DAL.Entity;
using DAL.Persistencia;
using System.Configuration;
using BLL.Utils;
using System.Data;
using Site.Reports;
using DAL.DataSet;
using System.Data.SqlClient;
using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.Shared;
using System.IO;
using System.Web.Security;
using Site.Models;
using System.Threading.Tasks;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using Newtonsoft.Json;
using System.Net;
using System.Collections.Specialized;
using System.Globalization;


namespace Site.Controllers
{
    [Authorize]
    public class ClienteController : Controller
    {
        // GET: Cliente
        public ActionResult Index()
        {

            var c = new Cliente();
            c.Cliente_id = 0;
            ViewData["cliente"] = c;
            StartCliente();

            var mcli = new Cliente_Markup();
            mcli.Markup_id = 0;
            ViewData["markupcliente"] = mcli;

            return View("Clientes");
        }    

        public Usuarios ObterUser()
        {
            try
            {
                FormsIdentity id = (FormsIdentity)System.Web.HttpContext.Current.User.Identity;
                FormsAuthenticationTicket ticket = id.Ticket;
                return new UsuarioDAL().ObterPorEmail(ticket.Name);
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return null;
            }
        }

        #region Autocompletes

        public ActionResult ObterQuotations(string term, int user_id)
        {
            try
            {
                List<string> quots = new List<string>();

                //if (term.Equals("*"))
                //    quots = new QuotationDAL().ListarTodosString(term, user_id);
                //else
                quots = new QuotationDAL().ListarTodosString(term, user_id).Take(100).ToList();

                return Json(quots, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
                return null;
            }
        }

        public ActionResult ObterQuotations_copia(string term)
        {
            try
            {
                List<string> quots = new List<string>();
                quots = new QuotationDAL().ListarTodosString(term).Take(100).ToList();

                return Json(quots, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
                return null;
            }
        }

        public ActionResult ObterClientes(string term)
        {
            try
            {
                List<string> cls = new ClienteDAL().ListarTodos(term).Select(s => s.Cliente_nome).Distinct().Take(100).ToList();
                return Json(cls, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
                return null;
            }
        }

        public ActionResult ObterCidades(string term)
        {
            try
            {
                List<string> cls = new List<string>();

                if (term.Equals("*"))
                    cls = new CidadeDAL().ListarTodos().OrderBy(s => s.CID_nome).Select(s => s.CID_nome).Distinct().ToList();
                else
                    cls = new CidadeDAL().ListarTodos(term).Select(s => s.CID_nome).Distinct().Take(100).ToList();


                return Json(cls, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
                return null;
            }
        }

        public ActionResult ObterTransfers(string term, string cidade)
        {
            try
            {
                ServicoDAL ftd = new ServicoDAL();
                List<string> cls = new List<string>();

                if (!cidade.Equals(""))
                    cls = ftd.ListarTodosTrf(term, new CidadeDAL().ObterPorNome(cidade).CID_id).Select(s => s.Servicos_Nome).Distinct().ToList();
                else
                    cls = ftd.ListarTodosTrf(term).Select(s => s.Servicos_Nome).Distinct().Take(200).ToList();

                return Json(cls, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
                return null;
            }
        }

        public ActionResult ObterTours(string term, string cidade)
        {
            try
            {
                ServicoDAL ftd = new ServicoDAL();
                List<string> cls = new List<string>();

                if (!cidade.Equals(""))
                    cls = ftd.ListarTodosTor(term, new CidadeDAL().ObterPorNome(cidade).CID_id).Select(s => s.Servicos_Nome).Distinct().ToList();
                else
                    cls = ftd.ListarTodosTor(term).Select(s => s.Servicos_Nome).Distinct().Take(200).ToList();

                return Json(cls, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
                return null;
            }
        }

        public ActionResult ObterSuppliers(string term)
        {
            try
            {
                List<string> cls = new List<string>();

                cls = new SupplierDAL().ListarTodos(term).Select(s => s.S_nome).OrderBy(s => s).ToList();

                return Json(cls, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
                return null;
            }
        }

        public ActionResult ObterHoteis(string term, string cidade)
        {
            try
            {
                SupplierDAL ftd = new SupplierDAL();
                List<string> lst = new List<string>();

                if (!cidade.Equals(""))
                {
                    lst = ftd.FindAllTipo(term, 1, new CidadeDAL().ObterPorNome(cidade).CID_id).OrderBy(s => s.S_nome).Select(s => s.S_nome).ToList();
                }
                else
                {
                    lst = ftd.FindAllTipo(term, 1).OrderBy(s => s.S_nome).Select(s => s.S_nome).ToList();
                }

                return Json(lst, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
                return null;
            }
        }

        public ActionResult ObterPaxsGroups(string term, int user_id)
        {
            try
            {
                List<string> cls = new List<string>();

                cls = new QuotationGrupoDAL().ListarPaxsGroup(user_id, 0, term).ToList();

                return Json(cls, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
                return null;
            }
        }

        public ActionResult ObterSuppliers_Filtros(string term, int idStatus, int idTipoSupplier, int TipoPesquisa, int idCidade)
        {
            try
            {
                List<string> cls = new List<string>();

                cls = new SupplierDAL().ListarSupplier_Filtros(term, idStatus, idTipoSupplier, TipoPesquisa, idCidade);

                return Json(cls, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
                return null;
            }
        }

        public ActionResult ObterCategorias(string term)
        {
            try
            {
                TarifCategoriaDAL t = new TarifCategoriaDAL();
                List<Tarif_Categoria> tc = t.ListarTodos(term);

                List<string> lista = new List<string>();

                foreach (Tarif_Categoria p in tc)
                {
                    lista.Add(p.Tarif_categoria_nome);
                }

                return Json(lista, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
                return null;
            }
        }

        #endregion

        #region Clientes

        protected void StartCliente()
        {
            ViewBag.CliRepresentante = new ClienteDAL().ListarTodos();
            ViewBag.CliCentroCusto = new CentroCustoDAL().ListarTodosC_C();
            ViewBag.CliMercado = new MercadoDAL().ListarTodos();
            ViewBag.CliBaseTarifaria = new BaseTarifariaDAL().ListarTodos();
            var pais = new PaisDAL().ListarTodos();
            ViewBag.CliPais = pais;
            ViewBag.CliCidade = new CidadeDAL().ListarTodos(pais.First().PAIS_id);
        }

        protected List<Cliente> ObterClientes(int page = 0)
        {

            List<Cliente> alunos = new List<Cliente>();
            try
            {
                ClienteDAL ud = new ClienteDAL();
                List<Cliente> lista = ud.ListarTodos();

                const int PageSize = 20;

                var count = lista.Count;
                var data = lista.Skip(page * PageSize).Take(PageSize).ToList();

                decimal tot = ((decimal)count / (decimal)PageSize);

                if (tot > 1)
                {
                    string[] pars = Convert.ToDecimal(tot).ToString().Split(',');
                    if (pars.Count() > 1)
                    {
                        if (Convert.ToInt32(pars[1].First()) >= 1)
                        {
                            tot = tot + 1;
                            string[] pg = tot.ToString().Split(',');
                            tot = Convert.ToInt32(pg[0]);
                        }
                    }
                }

Site/Views/Cliente/Clientes.cshtml
@{
    ViewBag.Title = "Clientes";
    Layout = "~/Views/Shared/template.cshtml";
}

<section class="content-header">
    <h1>
        Clientes

        <small>Lista</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-group"></i>Clientes</a></li>
    </ol>
</section>

<section class="content">

    <div class="box">
        <div class="box-body">

            <div class="row">
                <div class="col-md-12">
                    <label for="txtProcurarClientes">Procurar</label>
                    <div class="input-group">
                        <span class="input-group-addon" id="basic-addon1"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></span>
                        <input id="txtProcurarClientes" type="text" class="form-control" aria-describedby="basic-addon1" placeholder="Nome Cliente">
                    </div>
                </div>
            </div>

        </div>
    </div>

    <div class="box box-primary">
        <div class="box-header with-border">
            <h4 id="tituloCliente">Cadastros</h4>
            <div class="box-tools pull-right">
                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            </div>
        </div><!-- /.box-header -->
        <div class="box-body">

            <div class="nav-tabs-custom">
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#tab_1" data-toggle="tab">Cliente</a></li>
                    <li><a href="#tab_2" data-toggle="tab">Markup</a></li>
                    <li><a href="#tab_3" data-toggle="tab">Contato</a></li>
                </ul>
                <div class="tab-content">

                    <div class="tab-pane active" id="tab_1">
                        <div class="row">
                            <div id="dvcliente">
                                @Html.Partial("_cliente_add", ViewData["cliente"])
                            </div>
                        </div>
                    </div>

                    <div class="tab-pane" id="tab_2">
                        <div class="row">
                            <div class="col-md-2">
                                <button id="btnAddMarkup" class="btn btn-success btn-sm" title="Adicionar Markup" style="border-radius:0px;">
                                    <i class="fa fa-plus" aria-hidden="true"></i> Adicionar Markup
                                </button>
                            </div>
                        </div>
                        <br />
                        <div id="dvmarkupcliente">
                        </div>
                    </div>

                    <div class="tab-pane" id="tab_3">

                    </div>


                </div>
            </div>

        </div>
    </div>
</section>


<div class="modal fade bs-example-modal-lg" id="modalMarkupCliente" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Markup Cliente</h4>
            </div>

            <div class="modal-body">

               <div id="dvmarkupclienteadd">
                   @Html.Partial("_markupCliente_add", ViewData["markupcliente"])
               </div>

            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            </div>

        </div>
    </div>
</div>

<script type="text/javascript">
    $('#txtProcurarClientes').autocomplete({
        source: "@Url.Action("ObterClientes", "Cliente")",
        minLength: 3,
        select: function (e, ui) {
            $.get("@Url.Action("ObterCliente", "Cliente")", { cliente: ui.item.value }, function (data) {
                $('#dvcliente').html(data);
                $('#txtProcurarClientes').val("");
            });
            ObterMarkups(ui.item.value);
        }
    });

    function ObterMarkups(cli) {
        $.get("@Url.Action("ObterMarkupsCliente", "Cliente")", { cliente: cli }, function (data) {
            $('#dvmarkupcliente').html(data);
        });
    }

    $('#btnAddMarkup').click(function () {
        $.get("@Url.Action("ObterMarkupCliente_Empty", "Cliente")", function (data) {
            $('#dvmarkupclienteadd').html(data);
            $('#CodClienteMk').val($('#idcliente').val());
            $('#modalMarkupCliente').modal();
        });        
        //$('#modalMarkupCliente').modal();
    });

</script>

Site/Views/Cliente/_cliente_add.cshtml
@model DAL.Entity.Cliente

<form role="form" id="form-cliente" method="post" action="javascript:func()">

    <input type="hidden" id="idcliente" name="Cliente_id" value="@Model.Cliente_id" />

    <div class="col-md-6">
        <div class="row">
            <div class="col-md-12">
                <label for="txtNomeCliente">Nome Cliente</label>
                <input id="txtNomeCliente" type="text" name="Cliente_nome" class="form-control" placeholder="Nome do Cliente" required="required" value="@Model.Cliente_nome" />
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-12">
                <label for="txtEndCliente">Endereço Cliente</label>
                <textarea id="txtEndCliente" class="form-control" name="Cliente_endereco" placeholder="Endereço Cliente">@Model.Cliente_endereco</textarea>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-12">
                <label for="txtSiteCliente">Site Cliente</label>
                <input id="txtSiteCliente" type="text" name="Cliente_http" class="form-control" placeholder="Site do Cliente" value="@Model.Cliente_nome" />
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-12">
                <label for="txtCepCliente">Cep</label>
                <input id="txtCepCliente" type="text" name="Cliente_cep" class="form-control" placeholder="Cep do Cliente" value="@Model.Cliente_cep" />
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-12">
                <label for="txtTelCliente">Telefone Cliente</label>
                <input id="txtTelCliente" type="text" name="Cliente_telefone" class="form-control" placeholder="Telefone do Cliente" value="@Model.Cliente_telefone" />
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-12">
                <label for="txtFaxCliente">Fax Cliente</label>
                <input id="txtFaxCliente" type="text" name="Cliente_fax" class="form-control" placeholder="Fax do Cliente" value="@Model.Cliente_fax" />
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-12">
                <label for="txtEmailCliente">Email Cliente</label>
                <input id="txtEmailCliente" type="email" name="Cliente_email" class="form-control" placeholder="Email do Cliente" required="required" value="@Model.Cliente_email" />
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-2">
                <input id="btnSalvarCliente" type="submit" class="btn btn-primary" title="Salvar" value="Salvar" style="border-radius:0px;" />
            </div>
            <div class="col-md-1">                
                <input id="btnNovoCliente" type="button" class="btn btn-primary" title="Novo" value="Novo" style="border-radius:0px;" />
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="row">
            <div class="col-md-12">
                <label>Since</label>
                <input id="txtSinceCliente" name="Cliente_since" type="date" class="form-control" value="@Model.Cliente_since" />
            </div>
        </div>
        <br />

        <div class="row">
            <div class="col-md-12">
                <label for="ddlRepresentanteCliente">Representante</label>
                <select id="ddlRepresentanteCliente" class="form-control" name="Representante_id">
                    <option value="0">Selecione</option>
                    @foreach (var item in ViewBag.CliRepresentante)
                    {
                    <option value="@item.Cliente_id">@item.Cliente_nome</option>
                    }
                </select>
            </div>
        </div>
        <br />

        <div class="row">
            <div class="col-md-12">
                <label for="ddlCentroCustoCliente">Centro Custo</label>
                <select id="ddlCentroCustoCliente" class="form-control" name="CentroCusto_id">
                    <option value="0">Selecione</option>
                    @foreach (var item in ViewBag.CliCentroCusto)
                    {
                    <option value="@item.CentroCusto_id">@item.CentroCusto_nome</option>
                    }
                </select>
            </div>
        </div>
        <br />

        <div class="row">
            <div class="col-md-12">
                <label for="ddlMercadoCliente">Mercado</label>
                <select id="ddlMercadoCliente" class="form-control" name="Mercado_id">
                    <option value="0">Selecione</option>
                    @foreach (var item in ViewBag.CliMercado)
                    {
                    <option value="@item.Mercado_id">@item.Mercado_nome</option>
                    }
                </select>
            </div>
        </div>
        <br />

        <div class="row">
            <div class="col-md-12">
                <label for="ddlBaseTarifariaCliente">BaseTarifaria</label>
                <select id="ddlBaseTarifariaCliente" class="form-control" name="BaseTarifaria_id">
                    <option value="0">Selecione</option>
                    @foreach (var item in ViewBag.CliBaseTarifaria)
                    {
                    <option value="@item.BaseTarifaria_id">@item.BaseTarifaria_nome</option>
                    }
                </select>
            </div>
        </div>
        <br />

        <div class="row">
            <div class="col-md-12">
                <label for="ddlPaisCliente">País</label>
                <select id="ddlPaisCliente" class="form-control" name="PAIS_id" onchange="ChangePaisCliente()">
                    <option value="0">Selecione</option>
                    @foreach (var item in ViewBag.CliPais)
                    {
                    <option value="@item.PAIS_id">@item.PAIS_nome</option>
                    }
                </select>
            </div>
        </div>
        <br />

        <div class="row">
            <div class="col-md-12">
                <label for="ddlCidadeCliente">Cidade</label>
                <div id="dvddlCidadeCliente">
                    <select id="ddlCidadeCliente" class="form-control" name="CID_id">
                        <option value="0">Selecione</option>
                        @foreach (var item in ViewBag.CliCidade)
                        {
                        <option value="@item.CID_id">@item.CID_nome</option>
                        }
                    </select>
                </div>
            </div>
        </div>
        <br />

    </div>



</form>


<script type="text/javascript">

    if(@Model.Cliente_id != 0){

        $('#ddlRepresentanteCliente').val(@Model.Representante_id);
        $('#ddlCentroCustoCliente').val(@Model.CentroCusto_id);
        $('#ddlMercadoCliente').val(@Model.Mercado_id);
        $('#ddlBaseTarifariaCliente').val(@Model.BaseTarifaria_id);
        $('#ddlPaisCliente').val(@Model.PAIS_id);
        $('#ddlCidadeCliente').val(@Model.CID_id);
        //ChangePaisCliente();
    }

    function ChangePaisCliente() {
        $.get("@Url.Action("ObterCidadesDrop", "Cliente")", { idPais: $('#ddlPaisCliente').val() }, function (data) {
            $('#dvddlCidadeCliente').html(data);

            if(@Model.Cliente_id != 0){
                $('#ddlCidadeCliente').val();
            }
        });

    }

    $('#btnNovoCliente').click(function(){
        location.reload();
        //$('#form-cliente')[0].reset();
    });

    $('#form-cliente').submit(function(){
        $('#btnSalvarCliente').html('Aguarde...');
        $('#btnSalvarCliente').attr("disabled", "disabled");

        var mod = $(this).serialize();
        toastr.options = { closeButton: true, newestOnTop: false, progressBar: true, onclick: null, showDuration: "300", positionClass: "toast-top-right" };
        waitingDialog.show('Aguarde...', { dialogSize: 'sm', progressType: 'warning' });

        var url = "";
        if($('#idcliente').val() == 0){
            url = "@Url.Action("SalvarCliente", "Cliente")";
        }else{
            url = "@Url.Action("AtualizarCliente", "Cliente")";
        }

        $.ajax({
            url: url,
            data: mod,
            type: "POST",
            success: function (d) {
                if (d.success) {
                    var $toast = toastr["success"](d.message, "Prosoftware");
                    $toastlast = $toast;
                }
                else {
                    var $toast = toastr["error"](d.message, "Prosoftware");
                    $toastlast = $toast;
                }
                $('#btnSalvarCliente').removeAttr("disabled");
                $('#btnSalvarCliente').html('Salvar');
                $('#idcliente').val(d.cod);
                waitingDialog.hide();
                //$('#form-cliente')[0].reset();
            },
            error: function (XHR) {
                waitingDialog.hide(); alert(XHR);
            }
        });
    });

</script>

Site/Views/Cliente/_lst_clientes.cshtml
@model IEnumerable<DAL.Entity.Cliente>


<table class="table table-bordered table-striped">

    <thead>

        <tr>
            <th class="small">Nome</th>
            <th class="small">País</th>
            <th class="small">Cidade</th>
            <th class="small">Editar</th>
        </tr>

    </thead>

    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td class="small" style="width: 200px;">@item.Cliente_nome</td>
                <td class="small" style="width: 20px;">@item.Pais.PAIS_nome</td>
                <td class="small">@item.Cidade.CID_nome</td>
                <td>
                    <button id="btnEditar" type="button" value='@item.CID_id°@item.Cliente_nome' class="btn btn-xs btn-success editarcliente" title="Editar"><span class="glyphicon glyphicon-pencil"></span></button>
                    <button id="btnDeletar" type="button" value='@item.CID_id°@item.Cliente_nome' class="btn btn-xs btn-danger deletarcliente" title="Deletar"><span class="glyphicon glyphicon-trash"></span></button>
                </td>
            </tr>
        }

    </tbody>

</table>

@if (ViewBag.Pages > 1)
{
    for (int i = 0; i < ViewBag.Pages; i++)
    {
        <input type="button" class="btn btn-default btnPag" value="@i" />
    }
}



<script type="text/javascript">

    $('.btnPag').click(function (e) {
        var pg = $(this).val();
        $.ajax({
            type: "GET",
            url: "@Url.Action("PagClientes", "Cliente")",
            data: { page: pg },
            success: function (data) {
                $('#lstclientes').html(data);
            },
            error: function (xhr) { alert('error'); }
        });
    });

</script>

Site/Views/Cliente/_lst_markupCliente.cshtml
@if (ViewBag.MarkupCliente != null)
{
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Inicial</th>
                <th>Final</th>
                <th>Hotel</th>
                <th>Desc Hotel</th>
                <th>Serviço</th>
                <th>Desc Serviço</th>
                <th>Seasonal</th>
                <th>Meal</th>
                <th>Editar</th>
            </tr>
        </thead>

        <tbody>
            @foreach (var item in ViewBag.MarkupCliente)
                {
                <tr>
                    <td>@string.Format("{0:dd/MM/yyyy}", item.Markup_dataInicial)</td>
                    <td>@string.Format("{0:dd/MM/yyyy}", item.Markup_dataFinal)</td>
                    <td>@item.Markup_hotel</td>
                    <td>@item.Markup_descontoHotel</td>
                    <td>@item.Markup_servico</td>
                    <td>@item.Markup_descontoServico</td>
                    <td>@item.Markup_seasonal</td>
                    <td>@item.Markup_meals</td>
                    <td>
                        <button type="button" value="@item.Markup_id" class="btn btn-xs btn-success ediatrmarkupcliente" title="Editar"><span class="glyphicon glyphicon-pencil"></span></button>
                        <button type="button" value="@item.Markup_id" class="btn btn-xs btn-danger deletarmarkupcliente" title="Deletar"><span class="glyphicon glyphicon-trash"></span></button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}


<script type="text/javascript">

    $('.ediatrmarkupcliente').click(function () {
        $.get("@Url.Action("ObterMarkupCliente_id", "Cliente")", { id: $(this).val() }, function (data) {
            $('#dvmarkupclienteadd').html(data);
            $('#modalMarkupCliente').modal();
        });
    });

    $('.deletarmarkupcliente').click(function () {
        var result = window.confirm('Deseja realmente excluir esse markup?');
        if (result == false) {
            e.preventDefault();
            return;
        };

        $.get("@Url.Action("DeletarMarkupCliente", "Cliente")", { id: $(this).val(), cliente: $('#txtNomeCliente').val() }, function (data) {
            $('#dvmarkupcliente').html(data);            
        });
    });

</script>