Site/Controllers/CadastrosController.cs
using DAL.Entity;
using DAL.Persistencia;
using Site.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Site.Controllers
{
    [Authorize]
    public class CadastrosController : Controller
    {
        // GET: Cadastros
        public ActionResult Index()
        {
            StartCadastros();
            return View();
        }

        protected void StartCadastros()
        {
            ViewData["pais"] = new Pais();
            ViewData["cidade"] = new Cidade();
            ViewData["mercado"] = new Mercado();
            ViewData["basetarifaria"] = new BaseTarifaria();
            ViewData["moeda"] = new Moeda();
            ViewData["rede"] = new S_Rede();
            ViewData["temporada"] = new S_Mercado_Estacao();
            ViewData["meal"] = new S_Meal();
            ViewData["categApto"] = new Tarif_Categoria();
            ViewData["categHotel"] = new S_Categoria_Escrita();
            ViewData["tipoServico"] = new S_Servicos_Tipo();
            ViewData["categoria"] = new S_Servicos_Tipo_Categ();
            ViewData["subtipo"] = new SubItem();
            ViewData["subitem"] = new ItemSubServico();
            ViewData["classificacao"] = new S_Categoria();
            ViewData["amenitie"] = new S_Amenities();


            var pa = new PaisDAL().ListarTodos();
            ViewBag.paises = pa;
            ViewBag.CidPais = pa;

            ViewBag.cidades = new CidadeDAL().ListarTodos();
            ViewBag.mercados = new MercadoDAL().ListarTodos();
            ViewBag.basetarifarialst = new BaseTarifariaDAL().ListarTodos();
            ViewBag.moedas = new MoedaDAL().ListarTodos();
            ViewBag.redes = new RedeDAL().ListarTodos();
            ViewBag.temporadas = new MercadoEstacaoDAL().ListarTodos();
            ViewBag.meals = new MealDAL().ListarTodos_SMeal();
            ViewBag.categAptos = new TarifCategoriaDAL().ListarTodos();
            ViewBag.categhoteis = new CategoriaEscritaDAL().ListarTodos("");
            ViewBag.tiposervicos = new ServicoTipoDAL().ListarTodos();
            ViewBag.categorias = new ServicoTipoCategDAL().ListarTodos();
            ViewBag.TipoServCategoria = new ServicoTipoDAL().ListarTodos();
            ViewBag.subtipos = new SubItemDAL().ListarTodos();
            ViewBag.subitens = new ItemSubServicoDAL().ListarTodos();
            ViewBag.classificacoes = new CategoriaDAL().ListarTodos();

            ViewBag.amenities = new AmenitiesDAL().ListarTodos();
            ViewBag.ddlGroupAmenities = new GroupAmenitiesDAL().ListarTodos();
        }

        #region Autocompletes       

        public ActionResult ObterAmenities(string term)
        {
            try
            {
                List<string> cls = new List<string>();

                cls = new AmenitiesDAL().ListarTodos(term).Select(s => s.S_Amenities_nome).Distinct().ToList();

                return Json(cls, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
                return null;
            }
        }

        public ActionResult ObterClassificacao(string term)
        {
            try
            {
                List<string> cls = new List<string>();

                cls = new CategoriaDAL().ListarTodos(term).Select(s => s.Categ_classificacao).Distinct().ToList();

                return Json(cls, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
                return null;
            }
        }

        public ActionResult ObtersubItem(string term)
        {
            try
            {
                List<string> cls = new List<string>();

                cls = new ItemSubServicoDAL().ListarTodos(term).Select(s => s.ItemSubServico_nome).Distinct().ToList();

                return Json(cls, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
                return null;
            }
        }

        public ActionResult ObterSubTipos(string term)
        {
            try
            {
                List<string> cls = new List<string>();

                cls = new SubItemDAL().ListarTodos(term).Select(s => s.SubItem_nome).Distinct().ToList();

                return Json(cls, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
                return null;
            }
        }

        public ActionResult ObterCategoria(string term)
        {
            try
            {
                List<string> cls = new List<string>();

                cls = new ServicoTipoCategDAL().ListarTodos(term).Select(s => s.Tipo_categ_nome).Distinct().ToList();

                return Json(cls, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
                return null;
            }
        }

        public ActionResult ObterTipoServico(string term)
        {
            try
            {
                List<string> cls = new List<string>();

                cls = new ServicoTipoDAL().ListarTodos(term).Select(s => s.Tipo_Nome).Distinct().ToList();

                return Json(cls, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
                return null;
            }
        }

        public ActionResult ObterCategHotel(string term)
        {
            try
            {
                List<string> cls = new List<string>();

                cls = new CategoriaEscritaDAL().ListarTodos(term).Select(s => s.CategoriaEscrita_nome).Distinct().ToList();

                return Json(cls, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
                return null;
            }
        }

        public ActionResult ObterTarifCateg(string term)
        {
            try
            {
                List<string> cls = new List<string>();

                cls = new TarifCategoriaDAL().ListarTodos(term).Select(s => s.Tarif_categoria_nome).Distinct().ToList();

                return Json(cls, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
                return null;
            }
        }

        public ActionResult ObterMeal(string term)
        {
            try
            {
                List<string> cls = new List<string>();

                cls = new MealDAL().ListarTodos_SMeal(term).Select(s => s.S_meal_nome).Distinct().ToList();

                return Json(cls, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
                return null;
            }
        }

        public ActionResult ObterTemporada(string term)
        {
            try
            {
                List<string> cls = new List<string>();

                cls = new MercadoEstacaoDAL().ListarTodos(term).Select(s => s.S_mercado_estacao_nome).Distinct().ToList();

                return Json(cls, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
                return null;
            }
        }

        public ActionResult ObterRede(string term)
        {
            try
            {
                List<string> cls = new List<string>();

                cls = new RedeDAL().ListarTodos(term).Select(s => s.Rede_nome).Distinct().ToList();

                return Json(cls, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
                return null;
            }
        }

        public ActionResult ObterMoeda(string term)
        {
            try
            {
                List<string> cls = new List<string>();

                cls = new MoedaDAL().ListarTodos(term).Select(s => s.Moeda_nome).Distinct().ToList();

                return Json(cls, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
                return null;
            }
        }

        public ActionResult ObterBaseTarifaria(string term)
        {
            try
            {
                List<string> cls = new List<string>();

                cls = new BaseTarifariaDAL().ListarTodos(term).Select(s => s.BaseTarifaria_nome).Distinct().ToList();

                return Json(cls, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
                return null;
            }
        }

        public ActionResult ObterMercados(string term)
        {
            try
            {
                List<string> cls = new List<string>();

                cls = new MercadoDAL().ListarTodos(term).Select(s => s.Mercado_nome).Distinct().ToList();

                return Json(cls, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
                return null;
            }
        }

        public ActionResult ObterPaises(string term)
        {
            try
            {
                List<string> cls = new List<string>();

                cls = new PaisDAL().ListarTodos(term).Select(s => s.PAIS_nome).Distinct().ToList();

                return Json(cls, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
                return null;
            }

Site/Views/Cadastros/_cad_amenities.cshtml
@model DAL.Entity.S_Amenities

<div class="row">

    <form action="/Cadastros/UploadAmenities" enctype="multipart/form-data" method="post">

        <input type="hidden" id="idAmenities" name="S_Amenities_id" value="@Model.S_Amenities_id" />

        <div class="col-md-4">
            <div class="row">
                <div class="col-md-12">
                    <label for="txtNomeAmenities">Nome Amenities</label>
                    <input id="txtNomeAmenities" type="text" name="S_Amenities_nome" class="form-control" placeholder="Amenities" required value="@Model.S_Amenities_nome" />
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-12">
                    <label for="ddlGroupAmenities">Grupo</label>
                    <select id="ddlGroupAmenities" class="form-control" name="S_GroupAmenities_ID">                        
                        @foreach (var item in ViewBag.ddlGroupAmenities)
                        {
                            <option value="@item.S_GroupAmenities_ID">@item.S_GroupAmenities_Name</option>
                        }
                    </select>
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-12">
                    <input type="file" name="FilesAmenities" id="FilesAmenities" required class="btn btn-primary" />
                </div>
            </div>
            <br />
            @if (ViewBag.messageAmenities != null)
            {
                <div class="alert alert-success alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <h4>	<i class="icon fa fa-check"></i> Alert!</h4>
                    @ViewBag.messageAmenities
                </div>
                <br />
            }

            <div class="row">
                <div class="col-md-3">
                    <input type="submit" name="submit" value="Salvar" class="btn btn-primary" />
                </div>
            </div>
        </div>
    </form>

    <div class="col-md-8">

        <div class="row">
            <div class="col-md-12" style="height: 300px; overflow-y: auto;">
                <div id="dvlstamenities">
                    @Html.Partial("_lst_amenities")
                </div>
            </div>
        </div>

    </div>

</div>


<script type="text/javascript">


    $('#txtNomeAmenities').autocomplete({
        source: "@Url.Action("ObterAmenities", "Cadastros")",
        minLength: 3,
        select: function (e, ui) {
           
        }
    });

</script>

Site/Views/Cadastros/_cad_categApto.cshtml
@model DAL.Entity.Tarif_Categoria

<form role="form" id="form-TarifCateg" method="post" action="javascript:func()">

    <input type="hidden" id="idTarifCateg" name="Tarif_categoria_id" value="@Model.Tarif_categoria_id" />

    <div class="row">

        <div class="col-md-4">
            <div class="row">
                <div class="col-md-12">
                    <label for="txtNomeTarifCateg">Nome Categoria</label>
                    <input id="txtNomeTarifCateg" type="text" name="Tarif_categoria_nome" class="form-control" placeholder="Categoria" required value="@Model.Tarif_categoria_nome" />
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-3">
                    <input id="btnSalvarTarifCateg" type="submit" class="btn btn-primary btn-sm" title="Salvar" value="Salvar" style="border-radius:0px;" />
                </div>
                <div class="col-md-2">
                    <input id="btnExcluirTarifCateg" type="button" class="btn btn-primary btn-sm" title="Excluir" value="Excluir" style="border-radius:0px;" />
                </div>
                <div class="col-md-1">
                    <input id="btnNovoTarifCateg" type="button" class="btn btn-primary btn-sm" title="Novo" value="Novo" style="border-radius:0px;" />
                </div>
            </div>
        </div>


        <div class="col-md-8">

            <div class="row">
                <div class="col-md-12" style="height: 300px; overflow-y: auto;">

                    <table class="table table-bordered table-striped">

                        <thead>

                            <tr>
                                <th><small>Nome</small></th>
                            </tr>

                        </thead>

                        <tbody>
                            @foreach (var item in ViewBag.categAptos)
                            {
                                <tr>
                                    <td><small>@item.Tarif_categoria_nome</small></td>
                                </tr>
                            }
                        </tbody>

                    </table>

                </div>
            </div>

        </div>

    </div>

</form>


<script type="text/javascript">


    $('#btnExcluirTarifCateg').hide();
    $('#btnNovoTarifCateg').hide();

    $('#form-TarifCateg').submit(function () {

        toastr.options = { closeButton: true, newestOnTop: false, progressBar: true, onclick: null, showDuration: "300", positionClass: "toast-top-right" };
        waitingDialog.show('Aguarde...', { dialogSize: 'sm', progressType: 'warning' });

        var mod = $(this).serialize();

        $.ajax({
            url: "@Url.Action("SalvarTarifCateg", "Cadastros")",
            data: mod,
            type: "POST",
            success: function (d) {
                if (d.success) {
                    var $toast = toastr["success"](d.message, "Prosoftware");
                    $toastlast = $toast;

                    $('#idTarifCateg').val(d.cod);
                }
                else {
                    var $toast = toastr["error"](d.message, "Prosoftware");
                    $toastlast = $toast;
                }
                waitingDialog.hide();
            },
            error: function (XHR) {
                waitingDialog.hide(); alert(XHR);
            }
        });
    });

    $('#btnExcluirTarifCateg').click(function () {

        var result = window.confirm('Excluindo esse item, tudo linkado ao mesmo também será excluído. Confirma?');
        if (result == false) {
            e.preventDefault();
            return;
        };

        toastr.options = { closeButton: true, newestOnTop: false, progressBar: true, onclick: null, showDuration: "300", positionClass: "toast-top-right" };

        $.get("@Url.Action("ExcluirTarifCateg", "Cadastros")", { idTarifCateg: $('#idTarifCateg').val() }, function (d) {
            var $toast = toastr["success"](d.message, "Prosoftware");
            $toastlast = $toast;
            clear();
        });

    });


    $('#btnNovoTarifCateg').click(function () {
        clear();
    });

    function clear() {
        $('#idTarifCateg').val("0");
        $('#txtNomeTarifCateg').val("");
        $('#btnSalvarTarifCateg').val("Salvar");
        $('#btnExcluirTarifCateg').hide();
        $('#btnNovoTarifCateg').hide();
    }

    $('#txtNomeTarifCateg').autocomplete({
        source: "@Url.Action("ObterTarifCateg", "Cadastros")",
        minLength: 3,
        select: function (e, ui) {
            getTarifCateg(ui.item.value);

        }
    });

    function getTarifCateg(tarifCategnome) {
        $.get("@Url.Action("GetTarifCateg", "Cadastros")", { tarifCateg: tarifCategnome  }, function (data) {
            $('#dvTarifCateg').html(data);
            $('#btnSalvarTarifCateg').val("Atualizar");
            $('#btnExcluirTarifCateg').show();
            $('#btnNovoTarifCateg').show();
        });
    }

</script>

Site/Views/Cadastros/_cad_categHotel.cshtml
@model DAL.Entity.S_Categoria_Escrita

<form role="form" id="form-CategHotel" method="post" action="javascript:func()">

    <input type="hidden" id="idCategHotel" name="CategoriaEscrita_id" value="@Model.CategoriaEscrita_id" />

    <div class="row">

        <div class="col-md-4">
            <div class="row">
                <div class="col-md-12">
                    <label for="txtNomeCategHotel">Nome Categoria</label>
                    <input id="txtNomeCategHotel" type="text" name="CategoriaEscrita_nome" class="form-control" placeholder="Categoriaã" required value="@Model.CategoriaEscrita_nome" />
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-3">
                    <input id="btnSalvarCategHotel" type="submit" class="btn btn-primary btn-sm" title="Salvar" value="Salvar" style="border-radius:0px;" />
                </div>
                <div class="col-md-2">
                    <input id="btnExcluirCategHotel" type="button" class="btn btn-primary btn-sm" title="Excluir" value="Excluir" style="border-radius:0px;" />
                </div>
                <div class="col-md-1">
                    <input id="btnNovoCategHotel" type="button" class="btn btn-primary btn-sm" title="Novo" value="Novo" style="border-radius:0px;" />
                </div>
            </div>
        </div>


        <div class="col-md-8">

            <div class="row">
                <div class="col-md-12" style="height: 300px; overflow-y: auto;">

                    <table class="table table-bordered table-striped">

                        <thead>

                            <tr>
                                <th><small>Nome</small></th>
                            </tr>

                        </thead>

                        <tbody>
                            @foreach (var item in ViewBag.categhoteis)
                            {
                                <tr>
                                    <td><small>@item.CategoriaEscrita_nome</small></td>
                                </tr>
                            }
                        </tbody>

                    </table>

                </div>
            </div>

        </div>

    </div>

</form>


<script type="text/javascript">


    $('#btnExcluirCategHotel').hide();
    $('#btnNovoCategHotel').hide();

    $('#form-CategHotel').submit(function () {

        toastr.options = { closeButton: true, newestOnTop: false, progressBar: true, onclick: null, showDuration: "300", positionClass: "toast-top-right" };
        waitingDialog.show('Aguarde...', { dialogSize: 'sm', progressType: 'warning' });

        var mod = $(this).serialize();

        $.ajax({
            url: "@Url.Action("SalvarCategHotel", "Cadastros")",
            data: mod,
            type: "POST",
            success: function (d) {
                if (d.success) {
                    var $toast = toastr["success"](d.message, "Prosoftware");
                    $toastlast = $toast;

                    $('#idCategHotel').val(d.cod);
                }
                else {
                    var $toast = toastr["error"](d.message, "Prosoftware");
                    $toastlast = $toast;
                }
                waitingDialog.hide();
            },
            error: function (XHR) {
                waitingDialog.hide(); alert(XHR);
            }
        });
    });

    $('#btnExcluirCategHotel').click(function () {

        var result = window.confirm('Excluindo esse item, tudo linkado ao mesmo também será excluído. Confirma?');
        if (result == false) {
            e.preventDefault();
            return;
        };

        toastr.options = { closeButton: true, newestOnTop: false, progressBar: true, onclick: null, showDuration: "300", positionClass: "toast-top-right" };

        $.get("@Url.Action("ExcluirCategHotel", "Cadastros")", { idCategHotel: $('#idCategHotel').val() }, function (d) {
            var $toast = toastr["success"](d.message, "Prosoftware");
            $toastlast = $toast;
            clear();
        });

    });


    $('#btnNovoCategHotel').click(function () {
        clear();
    });

    function clear() {
        $('#idCategHotel').val("0");
        $('#txtNomeCategHotel').val("");
        $('#btnSalvarCategHotel').val("Salvar");
        $('#btnExcluirCategHotel').hide();
        $('#btnNovoCategHotel').hide();
    }

    $('#txtNomeCategHotel').autocomplete({
        source: "@Url.Action("ObterCategHotel", "Cadastros")",
        minLength: 3,
        select: function (e, ui) {
            getCategHotel(ui.item.value);

        }
    });

    function getCategHotel(categHotelnome) {
        $.get("@Url.Action("GetCategHotel", "Cadastros")", { categHotel: categHotelnome  }, function (data) {
            $('#dvCategHotel').html(data);
            $('#btnSalvarCategHotel').val("Atualizar");
            $('#btnExcluirCategHotel').show();
            $('#btnNovoCategHotel').show();
        });
    }

</script>

Site/Views/Cadastros/_cad_cidade.cshtml
@model DAL.Entity.Cidade

<form role="form" id="form-cidade" method="post" action="javascript:func()">

    <input type="hidden" id="idcidade" name="CID_id" value="@Model.CID_id" />

    <div class="row">

        <div class="col-md-4">
            <div class="row">
                <div class="col-md-12">
                    <label for="txtNomeCidade">Nome Cidade</label>
                    <input id="txtNomeCidade" type="text" name="CID_nome" class="form-control" placeholder="Nome Cidade" required value="@Model.CID_nome" />
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-6">
                    <label for="txtCidadeIata">Iata</label>
                    <input id="txtCidadeIata" type="text" name="CID_cod_Iata" class="form-control" placeholder="Iata" required value="@Model.CID_cod_Iata" />
                </div>
                <div class="col-md-6">
                    <label for="txtCidadeUF">UF</label>
                    <input id="txtCidadeUF" type="text" name="CID_uf" class="form-control" placeholder="UF" required value="@Model.CID_uf" />
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-6">                   
                    <label for="ddlPaisCidade">País</label>
                    <select id="ddlPaisCidade" class="form-control" name="PAIS_id">
                        <option value="0">Selecione</option>
                        @foreach (var item in ViewBag.CidPais)
                        {
                            <option value="@item.PAIS_id">@item.PAIS_nome</option>
                        }
                    </select>
                </div>
            </div>
            <br />
            <div class="row">

            </div>
            <br />
            <div class="row">
                <div class="col-md-3">
                    <input id="btnSalvarCidade" type="submit" class="btn btn-primary btn-sm" title="Salvar" value="Salvar" style="border-radius:0px;" />
                </div>
                <div class="col-md-2">
                    <input id="btnExcluirCidade" type="button" class="btn btn-primary btn-sm" title="Excluir" value="Excluir" style="border-radius:0px;" />
                </div>
                <div class="col-md-1">
                    <input id="btnNovoCidade" type="button" class="btn btn-primary btn-sm" title="Novo" value="Novo" style="border-radius:0px;" />
                </div>
            </div>
        </div>


        <div class="col-md-8">

            <div class="row">
                <div class="col-md-12" style="height: 300px; overflow-y: auto;">

                    <table class="table table-bordered table-striped">

                        <thead>

                            <tr>
                                <th><small>Iata</small></th>
                                <th><small>Nome</small></th>
                                <th><small>UF</small></th>                                
                            </tr>

                        </thead>

                        <tbody>
                            @foreach (var item in ViewBag.cidades)
                            {
                                <tr>
                                    <td><small>@item.CID_cod_Iata</small></td>
                                    <td><small>@item.CID_nome</small></td>
                                    <td><small>@item.CID_uf</small></td>                                   
                                </tr>
                            }
                        </tbody>

                    </table>

                </div>
            </div>

        </div>

    </div>

</form>


<script type="text/javascript">

    if (@Model.CID_id != 0)
    {
        $('#ddlPaisCidade').val('@Model.PAIS_id');
    }

    $('#btnExcluirCidade').hide();
    $('#btnNovoCidade').hide();

    $('#form-cidade').submit(function () {

        if ($('#ddlPaisCidade').val() == "0") {
            var $toast = toastr["error"]("Favor selecionar um País.", "Prosoftware");
            $toastlast = $toast;
            return false;
        }

        toastr.options = { closeButton: true, newestOnTop: false, progressBar: true, onclick: null, showDuration: "300", positionClass: "toast-top-right" };
        waitingDialog.show('Aguarde...', { dialogSize: 'sm', progressType: 'warning' });

        var mod = $(this).serialize();

        $.ajax({
            url: "@Url.Action("SalvarCidade", "Cadastros")",
            data: mod,
            type: "POST",
            success: function (d) {
                if (d.success) {
                    var $toast = toastr["success"](d.message, "Prosoftware");
                    $toastlast = $toast;

                    $('#idcidade').val(d.cod);
                }
                else {
                    var $toast = toastr["error"](d.message, "Prosoftware");
                    $toastlast = $toast;
                }
                waitingDialog.hide();
            },
            error: function (XHR) {
                waitingDialog.hide(); alert(XHR);
            }
        });
    });

    $('#btnExcluirCidade').click(function () {

        var result = window.confirm('Excluindo esse item, tudo linkado ao mesmo também será excluído. Confirma?');
        if (result == false) {
            e.preventDefault();
            return;
        };

        toastr.options = { closeButton: true, newestOnTop: false, progressBar: true, onclick: null, showDuration: "300", positionClass: "toast-top-right" };

        $.get("@Url.Action("ExcluirCidade", "Cadastros")", { idcidade: $('#idcidade').val() }, function (d) {
            var $toast = toastr["success"](d.message, "Prosoftware");
            $toastlast = $toast;
            clear();
        });

    });


    $('#btnNovoCidade').click(function () {
        clear();
    });

    function clear() {
        $('#idcidade').val("0");
        $('#txtNomeCidade').val("");
        $('#txtCidadeIata').val("");
        $('#txtCidadeUF').val("");
        $('#ddlPaisCidade').val('0');
        $('#btnSalvarCidade').val("Salvar");
        $('#btnExcluirCidade').hide();
        $('#btnNovoCidade').hide();
    }

    $('#txtNomeCidade').autocomplete({
        source: "@Url.Action("ObterCidades", "Cadastros")",
        minLength: 3,
        select: function (e, ui) {
            getPais(ui.item.value);

        }
    });

    function getPais(cidadenome) {
        $.get("@Url.Action("GetCidade", "Cadastros")", { cidade: cidadenome  }, function (data) {
            $('#dvcidade').html(data);
            $('#btnSalvarCidade').val("Atualizar");
            $('#btnExcluirCidade').show();
            $('#btnNovoCidade').show();
        });
    }

</script>

Site/Views/Cadastros/_lst_amenities.cshtml
<table class="table table-bordered table-striped">

    <thead>

        <tr>
            <th><small>Nome</small></th>
            <th><small>Grupo</small></th>
            <th><small>Img</small></th>
            <th><small>Excluir</small></th>
        </tr>

    </thead>

    <tbody>
        @foreach (var item in ViewBag.amenities)
        {
            <tr>
                <td><small>@item.S_Amenities_nome</small></td>
                <td><small>@item.S_GroupAmenities.S_GroupAmenities_Name</small></td>
                <td>
                    <small>
                        <img src="@string.Format("../iconsAmenities/{0}", item.S_Amenities_imgNome)" alt="..." style="width: 30px;" />
                    </small>
                </td>
                <td>
                    <button type="button" value="@item.S_Amenities_id" class="btn btn-xs btn-danger deletarsamenities" title="Deletar"><span class="glyphicon glyphicon-trash"></span></button>
                </td>
            </tr>
        }
    </tbody>

</table>

<script type="text/javascript">

    $('.deletarsamenities').click(function () {

        var result = window.confirm('Excluindo esse item, tudo linkado ao mesmo também será excluído. Confirma?');
        if (result == false) {
            e.preventDefault();
            return;
        };

        toastr.options = { closeButton: true, newestOnTop: false, progressBar: true, onclick: null, showDuration: "300", positionClass: "toast-top-right" };

        $.get("@Url.Action("ExcluirAmenitie", "Cadastros")", { idAmenitie: $(this).val() }, function (d) {

            if (d.success) {
                var $toast = toastr["success"](d.message, "Prosoftware");
                $toastlast = $toast;
                refreshgridamenities();
            } else {
                var $toast = toastr["error"](d.message, "Prosoftware");
                $toastlast = $toast;
            }
        });
    });

    function refreshgridamenities() {
        $.get("@Url.Action("refreshgridamenities", "Cadastros")", function (d) {
            $('#dvlstamenities').html(d);
        });
    }

</script>